name: CodeQL Testing

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11  # Replace '3.x' with your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt  # Adjust based on your project structure
    
    - name: Init CodeQL
      uses: github/codeql-action/init@v2

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
      with:
        language: python
        root-directory: src  # Specify the root directory for analysis

    - name: Analyze
      uses: github/codeql-action/analyze@v2
      with:
        language: python
        root-directory: src  # Specify the root directory for analysis

    - name: Upload CodeQL results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeql-sarif.sarif